replicaCount: 1

image:
  repository: localhost:5000/iiq-image

imagePullSecrets:
  - name: TBD

keystore:
  mountPath: /usr/local/keystore
  #To mount volumes using Kubernetes on Docker Desktop for Windows the path will be: /run/desktop/mnt/host/c/PATH_TO_FILE,
  #Here, the mount folder in hosting Windows is:
  #   C:/sailpoint/keystore
  #In macOS or Linux, just use normal path
  #path: /run/desktop/mnt/host/c/sailpoint/keystore
  hostPath: /Users/bruce.ren/Desktop/share-config/sailpoint/keystore
  
log:
  #To mount volumes using Kubernetes on Docker Desktop for Windows the path will be: /run/desktop/mnt/host/c/PATH_TO_FILE,
  #Here, the mount folder in hosting Windows is:
  #   C:/sailpoint/logs
  #In macOS or Linux, just use normal path  
  #path: /run/desktop/mnt/host/c/sailpoint/logs
  hostPath: /Users/bruce.ren/Desktop/share-config/sailpoint/logs

fullTextIndex:
  # This value should match the value of parameter 'FULL_TEXT_INDEX_PATH' to create Docker image.
  # For details, please refer to https://github.com/renliangfeng/iiq-container
  mountPath: /mnt/iiq-fulltext-index
  hostPath: /Users/bruce.ren/Desktop/share-config/sailpoint/iiq-fulltext-index

fileUploadPath:
  # This value should match the value of parameter 'UPLOAD_FILE_PATH' to create Docker image.
  # For details, please refer to https://github.com/renliangfeng/iiq-container
  mountPath: /mnt/file-upload
  hostPath: /Users/bruce.ren/Desktop/share-config/sailpoint/file-upload

spreadAZs:
  enabled: false

service:
  type: ClusterIP  
  port: 80
  
container:
  port: 8080

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

servers:
  ui:
    env:
      - name: TZ
        value: Australia/Canberra
      - name: IIQ_CONTAINER_HOSTNAME_DYNAMIC_TYPE
        value: UI
      - name: IIQ_CONTAINER_GENERATE_ALIAS
        value: "false"
  #task:
  #  env:
   #   - name: TZ
    #    value: Australia/Canberra
     # - name: IIQ_CONTAINER_HOSTNAME_DYNAMIC_TYPE
      #  value: TASK
      #- name: IIQ_CONTAINER_HOST_SERVICES
      #  value: Task,Request
      #- name: IIQ_CONTAINER_GENERATE_ALIAS
      #  value: "false"
