{{- range $type, $config := .Values.servers }}
{{- with (merge (dict "serverType" $type "serverConfig" $config) $) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .serverType }}
  labels:
    {{- include "podLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "podLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
{{- end }}